# Generated by Django 4.1.7 on 2023-03-07 16:55

from django.db import migrations, models
import netfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='arp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(null=True)),
                ('mac', netfields.fields.MACAddressField(null=True)),
                ('ipv4', netfields.fields.CidrAddressField(max_length=43, null=True)),
                ('vendor', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'arpalert_log',
            },
        ),
    ]
