# Generated by Django 4.1.7 on 2023-04-19 17:53

from django.db import migrations, models
import netfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='parsec_dns',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('id_count_start', models.SmallIntegerField()),
                ('id_request_name', models.SmallIntegerField()),
                ('responce_name', models.CharField(max_length=128)),
                ('ttl', models.IntegerField(null=True)),
                ('ipv4', netfields.fields.CidrAddressField(max_length=43)),
                ('redirect_port', models.IntegerField(null=True)),
                ('rec_time', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'PARSEC_DNS',
                'verbose_name_plural': 'PARSEC_DNS',
                'db_table': 'parsec_dns',
            },
        ),
    ]
